refactor: split declaration by event type
skyleague/event-horizon pull request #22
Opened 2022-09-03 16:10 UTC by pevisscher

2022-09-03 16:11 UTC, pevisscher commented
Current dependencies on/for this PR:
* main
  * **PR #11** <a href="https://app.graphite.dev/github/pr/skyleague/event-horizon/11" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #12** <a href="https://app.graphite.dev/github/pr/skyleague/event-horizon/12" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #14** <a href="https://app.graphite.dev/github/pr/skyleague/event-horizon/14" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #13** <a href="https://app.graphite.dev/github/pr/skyleague/event-horizon/13" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #15** <a href="https://app.graphite.dev/github/pr/skyleague/event-horizon/15" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #16** <a href="https://app.graphite.dev/github/pr/skyleague/event-horizon/16" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #17** <a href="https://app.graphite.dev/github/pr/skyleague/event-horizon/17" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                * **PR #18** <a href="https://app.graphite.dev/github/pr/skyleague/event-horizon/18" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                  * **PR #19** <a href="https://app.graphite.dev/github/pr/skyleague/event-horizon/19" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                    * **PR #20** <a href="https://app.graphite.dev/github/pr/skyleague/event-horizon/20" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                      * **PR #21** <a href="https://app.graphite.dev/github/pr/skyleague/event-horizon/21" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                        * **PR #22** <a href="https://app.graphite.dev/github/pr/skyleague/event-horizon/22" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
                          * **PR #23** <a href="https://app.graphite.dev/github/pr/skyleague/event-horizon/23" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                            * **PR #24** <a href="https://app.graphite.dev/github/pr/skyleague/event-horizon/24" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/skyleague/event-horizon/22?utm_source=stack-comment).

2022-09-05 06:41 UTC, MickVanDuijn requested changes
some discussion points for naming

2022-09-05 06:41 UTC, MickVanDuijn commented on src/lib/event.ts
> +export function kinesis<C, S, KinesisP, KinesisR, D>(
I'm afraid these names are too ambiguous, and will clash with application code (same for `http`, `sns`, etc). what about `kinesisHandler` or `kinesisEventHandler`?

2022-09-05 06:41 UTC, MickVanDuijn commented on src/lib/event.ts
> +export function event<H extends EventHandler>(definition: H): AWSLambdaHandler {
in light of the other comment, maybe we should rename this to `eventHandler`?

2022-09-05 08:18 UTC, MickVanDuijn approved these changes

2022-09-05 08:29 UTC, pevisscher commented
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/skyleague/event-horizon/22?utm_source=stack-comment).
<!-- SHOW_IN_GRAPHITE_UI -->

Job Reference: 74QS0D26BjCoc1fjew09

2022-09-05 09:53 UTC, pevisscher commented
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/skyleague/event-horizon/22?utm_source=stack-comment).
<!-- SHOW_IN_GRAPHITE_UI -->

Job Reference: MNQ6fIHHP2CutIWmkx44

2022-09-05 10:56 UTC, pevisscher commented
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/skyleague/event-horizon/22?utm_source=stack-comment).
<!-- SHOW_IN_GRAPHITE_UI -->

Job Reference: ZixEesAXj0mMWpqHV7EA

2022-09-05 10:57 UTC, merged