feat: add requestId to lambda context
skyleague/event-horizon pull request #40
Opened 2022-09-13 19:12 UTC by pevisscher

2022-09-13 19:12 UTC, pevisscher commented
Current dependencies on/for this PR:
* main
  * **PR #40** <a href="https://app.graphite.dev/github/pr/skyleague/event-horizon/40" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/skyleague/event-horizon/40?utm_source=stack-comment).

2022-09-14 16:19 UTC, MickVanDuijn requested changes
See inline comments

2022-09-14 16:19 UTC, MickVanDuijn commented on src/handlers/event.ts
> +import { randomUUID } from 'crypto'
Is this a compliant v4 uuid?

2022-09-14 16:19 UTC, MickVanDuijn commented on src/handlers/event.ts
> +        requestId: (requestIdGenerator === 'uuid' ? randomUUID : randomUUID)(),
I think it may be better to go with `requestTraceId`, since this one clashes with `awsRequestId` and `requestId` on the APIGW event

2022-09-14 16:19 UTC, MickVanDuijn commented on src/handlers/event.ts
>      async function handler(request: RawRequest, context: Context): Promise<RawResponse> {
it would be great if we can somehow inject the ID all the way at the beginning of this handler

2022-09-15 07:25 UTC, MickVanDuijn commented on src/handlers/event.ts
> +import { randomUUID } from 'crypto'
found my own answer 🙊  https://nodejs.org/api/crypto.html#cryptorandomuuidoptions

2022-09-20 08:30 UTC, MickVanDuijn approved these changes

2022-09-20 08:31 UTC, merged