docs: add initial readme
skyleague/event-horizon pull request #41
Opened 2022-09-15 08:49 UTC by loredanamoanga

2022-09-15 08:49 UTC, loredanamoanga commented
Current dependencies on/for this PR:
* main
  * **PR #41** <a href="https://app.graphite.dev/github/pr/skyleague/event-horizon/41" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/skyleague/event-horizon/41?utm_source=stack-comment).

2022-09-16 14:08 UTC, pevisscher requested changes

2022-09-16 14:08 UTC, pevisscher commented on README.md
> +  <img alt="Lines of code" src="https://img.shields.io/tokei/lines/github/skyleague/node-standards">
looks like there's still some references to node-standards

2022-09-19 16:52 UTC, pevisscher approved these changes

2022-09-23 07:23 UTC, merged